apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-devops
  template:
    metadata:
      labels:
        app: eks-devops
    spec:
      containers:
      - name: app
        image: <ECR_URI>:latest
        ports:
        - containerPort: 3000
